cc_binary(
    name = "hello_world",
    srcs = ["hello_world.cpp"],
    deps = [
        "@com_github_google_glog//:glog",
        "@project2//:util"
    ],
    visibility = ["//visibility:public"],
)
